server:
  servlet:
    context-path: /AadhaarApp
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/aadhaar?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver